# text2imgPS333.py

import streamlit as st
import requests

st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

st.image("https://i.ibb.co/hJVMdhNV/Photo-Fixer-Bot-aifaceswap-dac4ce0cdd00acf259c01808d4253130.jpg", width=250)
st.title("🔥 PS333 Image Generator 🔥")

prompt = st.text_input("Enter your prompt", placeholder="E.g. A tiger meditating on a mountain peak")
style = st.selectbox("Select Image Style", ["Realistic", "Cartoon", "Fantasy", "Cyberpunk", "Anime", "Photorealistic"])

if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):
            formatted_prompt = f"{style} style {prompt}".replace(" ", "%20")
            image_url = f"https://image.pollinations.ai/prompt/{formatted_prompt}"

            st.image(image_url, use_container_width=True, caption="Generated by ਪ੍ਰਭਵੀਰ ਸਿੰਘ Ai")
            st.success("✅ Image created! Ruko Zra Sabr Kro ✋")
            st.markdown(f"🔗 [Open Full Image]({image_url})")

            st.download_button(
                label="📥 Download Image",
                data=requests.get(image_url).content,
                file_name="generated_image.png",
                mime="image/png"
            )

st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
