import streamlit as st  # UI banaune lai
import requests          # Image download karan lai
import random            # Har vaar naya result den lai

# Page config
st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

# Logo image and title
# Tuhadi purani image link hi use kiti hai
st.image("https://i.ibb.co/hJVMdhNV/Photo-Fixer-Bot-aifaceswap-dac4ce0cdd00acf259c01808d4253130.jpg", width=250)
st.title("🔥 PS333 Image Generator 🔥")

# Prompt Input
prompt = st.text_input("Enter your prompt", placeholder="E.g. A tiger meditating on a mountain peak")

# Style Selection
style = st.selectbox("Select Image Style", ["Realistic", "Cartoon", "Fantasy", "Cyberpunk", "Anime", "Photorealistic"])

# Generate Button
if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):
            try:
                # 1. Random seed add kar rahe aa taan jo image refresh hove
                seed = random.randint(0, 999999)
                
                # 2. Prompt nu URL format vich convert karna
                formatted_prompt = f"{style} style {prompt}".replace(" ", "%20")
                
                # 3. Final URL with seed and no logo
                image_url = f"https://image.pollinations.ai/prompt/{formatted_prompt}?seed={seed}&nologo=true"

                # 4. Display the image directly from URL
                st.image(image_url, use_container_width=True, caption="Generated by ਪ੍ਰਭਵੀਰ ਸਿੰਘ Ai")
                st.success("✅ Image created! Ruko Zra Sabr Kro ✋")
                
                # 5. Full image link
                st.markdown(f"🔗 [Open Full Image]({image_url})")

                # 6. Download Button (eh background vich image fetch karke save karega)
                img_data = requests.get(image_url).content
                st.download_button(
                    label="📥 Download Image",
                    data=img_data,
                    file_name="ps333_generated_image.png",
                    mime="image/png"
                )
            except Exception as e:
                st.error(f"Kujh galti hoyi hai: {e}")

# Footer
st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
