import streamlit as st  # Streamlit library import kar rahe aa, jide naal UI banaune aa
import requests          # requests library import kar rahe aa taan jo image download kar sakiye

# Page config
# Eh line app da title, icon te layout set kar rahi aa
st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

# Logo image and title
# Eh line ch apa upar logo image laa rahe aa te app da title show kar rahe aa
st.image("https://i.ibb.co/hJVMdhNV/Photo-Fixer-Bot-aifaceswap-dac4ce0cdd00acf259c01808d4253130.jpg", width=250)
st.title("🔥 PS333 Image Generator 🔥")

# Prompt Input
# Eh input box aa jithe user apna prompt likhega (jo cheez generate karni aa)
prompt = st.text_input("Enter your prompt", placeholder="E.g. A tiger meditating on a mountain peak")

# Style Selection
# Eh dropdown menu aa jithe user image da style choose karega (Realistic, Cartoon, etc.)
style = st.selectbox("Select Image Style", ["Realistic", "Cartoon", "Fantasy", "Cyberpunk", "Anime", "Photorealistic"])

# Generate Button
# Eh button aa — jadon user click karega, ta image generate hovegi
if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        # Je prompt khali hoya, ta warning show hovegi
        st.warning("Please enter a valid prompt.")
    else:
        # Loading spinner jado tak image generate ho rahi aa
        with st.spinner("⏳ Generating your image..."):

            # Prompt nu format kar rahe aa URL lai, style v include kar rahe aa
            formatted_prompt = f"{style} style {prompt}".replace(" ", "%20")
            # Pollinations AI di API to image da URL bna rahe aa
            image_url = f"https://image.pollinations.ai/prompt/{formatted_prompt}"

            # Generated image show kar rahe aa te caption v likh rahe aa
            st.image(image_url, use_container_width=True, caption="Generated by ਪ੍ਰਭਵੀਰ ਸਿੰਘ Ai")
            st.success("✅ Image created! Ruko Zra Sabr Kro ✋")
            # Full image open karan lai link de rahe aa
            st.markdown(f"🔗 [Open Full Image]({image_url})")

            # Download button jide naal image file save ho jandi aa
            st.download_button(
                label="📥 Download Image",
                data=requests.get(image_url).content,
                file_name="generated_image.png",
                mime="image/png"
            )

# Footer
# Neeche footer vich apna naam te Instagram link show kar rahe aa
st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
